Repository ScuffleCloud/scuffle, pull requests merged in 2025-03, with the labels that each got.

#384 Adds builders for h264 sps structs + size of un/signed Exp-Golomb encoded numbers
  changes.d/pr-384.toml
  codecov.yml
  crates/expgolomb/src/lib.rs
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_header.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_packets.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_trailer.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_trailer.snap
  crates/flv/src/lib.rs
  crates/h264/src/config.rs
  crates/h264/src/io.rs
  crates/h264/src/lib.rs
  crates/h264/src/sps/chroma_sample_loc.rs
  crates/h264/src/sps/color_config.rs
  crates/h264/src/sps/frame_crop_info.rs
  crates/h264/src/sps/mod.rs
  crates/h264/src/sps/pic_order_count_type1.rs
  crates/h264/src/sps/sample_aspect_ratio.rs
  crates/h264/src/sps/sps_ext.rs
  crates/h264/src/sps/timing_info.rs
  crates/mp4/src/tests/demux.rs
  crates/transmuxer/src/codecs/avc.rs
  crates/transmuxer/src/lib.rs
Labels: B-brawl-merged

#388 more tests to scuffle-metrics
  changes.d/pr-388.toml
  crates/metrics/Cargo.toml
  crates/metrics/src/collector.rs
  crates/metrics/src/prometheus/mod.rs
  crates/metrics/src/value.rs
  valgrind_suppressions.log
Labels: B-brawl-merged

#393 chore(h3-webtransport): remove crate
  Cargo.lock
  Cargo.toml
  README.md
  codecov.yml
  crates/h3-webtransport/CHANGELOG.md
  crates/h3-webtransport/Cargo.toml
  crates/h3-webtransport/LICENSE.MIT
  crates/h3-webtransport/README.md
  crates/h3-webtransport/src/lib.rs
  crates/h3-webtransport/src/server.rs
  crates/h3-webtransport/src/session.rs
  crates/h3-webtransport/src/stream.rs
  crates/workspace-hack/Cargo.toml
Labels: B-brawl-merged, change-log-not-required

#392 fix missed test case in h264 pr
  crates/flv/src/lib.rs
  crates/h264/README.md
Labels: B-brawl-merged, change-log-not-required

#372 chore: deny lints and improved docs
  changes.d/pr-372.toml
  crates/aac/src/lib.rs
  crates/amf0/src/define.rs
  crates/amf0/src/lib.rs
  crates/av1/src/config.rs
  crates/av1/src/lib.rs
  crates/av1/src/obu/mod.rs
  crates/av1/src/obu/seq.rs
  crates/batching/src/batch.rs
  crates/batching/src/dataloader.rs
  crates/batching/src/lib.rs
  crates/bootstrap/derive/README.md
  crates/bootstrap/derive/src/lib.rs
  crates/bootstrap/src/config.rs
  crates/bootstrap/src/global.rs
  crates/bootstrap/src/lib.rs
  crates/bootstrap/src/service.rs
  crates/bootstrap/telemetry/src/lib.rs
  crates/bootstrap/telemetry/src/opentelemetry.rs
  crates/bytes-util/src/bytes_cursor.rs
  crates/bytes-util/src/lib.rs
  crates/context/src/ext.rs
  crates/context/src/lib.rs
  crates/expgolomb/src/lib.rs
  crates/ffmpeg/src/lib.rs
  crates/flv/src/lib.rs
  crates/future-ext/src/lib.rs
  crates/http/src/backend/h3/body.rs
  crates/http/src/backend/h3/mod.rs
  crates/http/src/backend/hyper/mod.rs
  crates/http/src/body.rs
  crates/http/src/error.rs
  crates/http/src/lib.rs
  crates/http/src/service/mod.rs
  crates/metrics/derive/src/lib.rs
  crates/metrics/src/collector.rs
  crates/metrics/src/lib.rs
  crates/nutype_enum/src/lib.rs
  crates/postcompile/src/lib.rs
  crates/pprof/src/lib.rs
  crates/settings/src/lib.rs
  crates/signal/src/bootstrap.rs
  crates/transmuxer/src/lib.rs
Labels: B-brawl-merged

#398 fix clippy lints
  crates/http/examples/src/axum.rs
  crates/http/examples/src/simple_service.rs
  crates/http/src/backend/h3/mod.rs
  crates/http/src/backend/hyper/stream.rs
  crates/metrics/derive/src/metrics_impl.rs
  crates/mp4/src/boxes/types/subs.rs
  crates/rtmp/src/chunk/tests/decoder.rs
Labels: B-brawl-merged, change-log-not-required

#400 fix scuffle-bootstrap no service panic
  changes.d/pr-400.toml
  crates/bootstrap/derive/src/lib.rs
  crates/bootstrap/derive/src/main_impl.rs
Labels: B-brawl-merged

#401 fix(http): readme
  changes.d/pr-401.toml
  crates/http/README.md
  crates/http/src/lib.rs
Labels: B-brawl-merged

#403 Fix/ci issue
  .github/scripts/ci-matrix-prep.py
  .github/workflows/ci.yaml
  deny.toml
Labels: B-brawl-merging, change-log-not-required

#410 Change shebangs in Justfile from '/bin/bash/' to '/usr/bin/env bash'
  Justfile
Labels: B-brawl-merged, change-log-not-required

#411 fix clippy lint
  crates/ffmpeg/src/filter_graph.rs
Labels: B-brawl-merged, change-log-not-required

#414 bump otel
  Cargo.lock
  changes.d/pr-414.toml
  crates/bootstrap/telemetry/Cargo.toml
  crates/metrics/Cargo.toml
  crates/metrics/examples/Cargo.toml
  crates/workspace-hack/Cargo.toml
Labels: B-brawl-merged

#413 bump h3
  Cargo.lock
  changes.d/pr-413.toml
  crates/http/Cargo.toml
  crates/workspace-hack/Cargo.toml
Labels: B-brawl-merged

#416 fix workspace-deps xtask tool
  dev-tools/xtask/src/cmd/workspace_deps.rs
Labels: B-brawl-merged, change-log-not-required

#419 chore: deny `unreachable_pub`
  Cargo.toml
  crates/aac/src/lib.rs
  crates/amf0/src/lib.rs
  crates/av1/src/lib.rs
  crates/av1/src/obu/utils.rs
  crates/batching/src/lib.rs
  crates/bootstrap/derive/src/lib.rs
  crates/bootstrap/derive/src/main_impl.rs
  crates/bootstrap/src/lib.rs
  crates/bootstrap/telemetry/src/lib.rs
  crates/bytes-util/src/lib.rs
  crates/context/src/lib.rs
  crates/expgolomb/src/lib.rs
  crates/ffmpeg/src/io/internal.rs
  crates/ffmpeg/src/lib.rs
  crates/future-ext/src/lib.rs
  crates/h264/src/lib.rs
  crates/http/src/backend/h3/utils.rs
  crates/http/src/backend/hyper/handler.rs
  crates/http/src/backend/hyper/stream.rs
  crates/http/src/backend/hyper/utils.rs
  crates/http/src/lib.rs
  crates/metrics/derive/src/enum_impl.rs
  crates/metrics/derive/src/lib.rs
  crates/metrics/derive/src/metrics_impl.rs
  crates/metrics/src/lib.rs
  crates/metrics/src/prometheus/mod.rs
  crates/nutype_enum/src/lib.rs
  crates/postcompile/src/deps.rs
  crates/postcompile/src/lib.rs
  crates/pprof/src/lib.rs
  crates/settings/src/lib.rs
  crates/signal/src/lib.rs
  crates/transmuxer/src/codecs/aac.rs
  crates/transmuxer/src/codecs/av1.rs
  crates/transmuxer/src/codecs/avc.rs
  crates/transmuxer/src/codecs/hevc.rs
  crates/transmuxer/src/codecs/mod.rs
  crates/transmuxer/src/lib.rs
Labels: B-brawl-merged, change-log-not-required

#420 refactor: remove example crates
  Cargo.lock
  Cargo.toml
  crates/batching/examples/Cargo.toml
  crates/batching/examples/LICENSE.Apache-2.0
  crates/batching/examples/LICENSE.MIT
  crates/batching/examples/README.md
  crates/batching/examples/src/dataloader.rs
  crates/bootstrap/Cargo.toml
  crates/bootstrap/examples/Cargo.toml
  crates/bootstrap/examples/LICENSE.Apache-2.0
  crates/bootstrap/examples/LICENSE.MIT
  crates/bootstrap/examples/README.md
  crates/bootstrap/examples/basic.rs
  crates/bootstrap/examples/cli.rs
  crates/bootstrap/examples/tracing.rs
  crates/http/Cargo.toml
  crates/http/examples/Cargo.toml
  crates/http/examples/LICENSE.Apache-2.0
  crates/http/examples/LICENSE.MIT
  crates/http/examples/README.md
  crates/http/examples/axum.rs
  crates/http/examples/echo.rs
  crates/http/examples/echo_tls.rs
  crates/metrics/Cargo.toml
  crates/metrics/examples/Cargo.toml
  crates/metrics/examples/LICENSE.Apache-2.0
  crates/metrics/examples/LICENSE.MIT
  crates/metrics/examples/README.md
  crates/metrics/examples/derive.rs
  crates/metrics/examples/prometheus.rs
  crates/postcompile/Cargo.toml
  crates/postcompile/src/features.rs
  crates/pprof/Cargo.toml
  crates/pprof/examples/Cargo.toml
  crates/pprof/examples/LICENSE.Apache-2.0
  crates/pprof/examples/LICENSE.MIT
  crates/pprof/examples/README.md
  crates/pprof/examples/cpu.rs
  crates/rtmp/Cargo.toml
  crates/rtmp/examples/Cargo.toml
  crates/rtmp/examples/LICENSE.Apache-2.0
  crates/rtmp/examples/LICENSE.MIT
  crates/rtmp/examples/README.md
  crates/rtmp/examples/basic.rs
  crates/settings/Cargo.toml
  crates/settings/examples/Cargo.toml
  crates/settings/examples/LICENSE.Apache-2.0
  crates/settings/examples/LICENSE.MIT
  crates/settings/examples/README.md
  crates/settings/examples/cli.rs
  crates/workspace-hack/Cargo.toml
  dev-tools/xtask/Cargo.toml
  dev-tools/xtask/src/cmd/change_logs/util.rs
  dev-tools/xtask/src/cmd/power_set/utils.rs
Labels: B-brawl-merged, change-log-not-required
