Repository ScuffleCloud/scuffle, pull requests merged in 2025-02, with the labels that each got.

#266 fix: ci clippy step
  .github/workflows/ci.yaml
  Justfile
  crates/batching/src/batch.rs
  crates/ffmpeg/src/log.rs
Labels: B-brawl-merged

#267 fix path for workspace hack dep
  Cargo.toml
Labels: B-brawl-merged

#270 fix linting for mp4 crate
  crates/mp4/src/boxes/types/padb.rs
Labels: B-brawl-merged

#271 disable code cov status check
  codecov.yml
Labels: B-brawl-merged

#269 ffmpeg docs
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  codecov.yml
  crates/ffmpeg/Cargo.toml
  crates/ffmpeg/README.md
  crates/ffmpeg/src/codec.rs
  crates/ffmpeg/src/consts.rs
  crates/ffmpeg/src/decoder.rs
  crates/ffmpeg/src/dict.rs
  crates/ffmpeg/src/encoder.rs
  crates/ffmpeg/src/error.rs
  crates/ffmpeg/src/filter_graph.rs
  crates/ffmpeg/src/frame.rs
  crates/ffmpeg/src/io/channel.rs
  crates/ffmpeg/src/io/input.rs
  crates/ffmpeg/src/io/internal.rs
  crates/ffmpeg/src/io/mod.rs
  crates/ffmpeg/src/io/output.rs
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_header.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_packets.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_trailer.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_header.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_packets.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_trailer.snap
  crates/ffmpeg/src/lib.rs
  crates/ffmpeg/src/limiter.rs
  crates/ffmpeg/src/log.rs
  crates/ffmpeg/src/packet.rs
  crates/ffmpeg/src/scalar.rs
  crates/ffmpeg/src/scaler.rs
  crates/ffmpeg/src/smart_object.rs
  crates/ffmpeg/src/snapshots/scuffle_ffmpeg__decoder__tests__test_decoder_audio.snap
  crates/ffmpeg/src/snapshots/scuffle_ffmpeg__decoder__tests__test_decoder_video.snap
  crates/ffmpeg/src/snapshots/scuffle_ffmpeg__encoder__tests__test_encoder_encode_video.snap
  crates/ffmpeg/src/stream.rs
  crates/ffmpeg/src/utils.rs
  crates/flv/Cargo.toml
  crates/flv/src/aac.rs
  crates/flv/src/audio.rs
  crates/flv/src/avc.rs
  crates/flv/src/lib.rs
  crates/flv/src/tag.rs
  crates/flv/src/video.rs
  crates/nutype_enum/Cargo.toml
  crates/nutype_enum/LICENSE.Apache-2.0
  crates/nutype_enum/LICENSE.MIT
  crates/nutype_enum/README.md
  crates/nutype_enum/src/lib.rs
  crates/workspace-hack/Cargo.toml
Labels: B-brawl-merged

#272 updated readme github actions badge
  README.md
Labels: B-brawl-merged

#273 fix: memory leaks in ffmpeg tests
  crates/ffmpeg/src/decoder.rs
  crates/ffmpeg/src/log.rs
Labels: B-brawl-merged

#283 fix windows for ffmpeg build
  crates/ffmpeg/CHANGELOG.md
  crates/ffmpeg/src/log.rs
  crates/ffmpeg/src/scaler.rs
Labels: B-brawl-merged

#284 bump ffmpeg version
  Cargo.lock
  Cargo.toml
  crates/ffmpeg/CHANGELOG.md
  crates/ffmpeg/Cargo.toml
Labels: B-brawl-merged

#281 add valgrind
  .github/workflows/ci.yaml
  .github/workflows/crate-release.yaml
  .gitignore
  Justfile
  crates/batching/Cargo.toml
  crates/batching/src/batch.rs
  crates/batching/src/dataloader.rs
  crates/bootstrap/src/global.rs
  crates/bootstrap/telemetry/Cargo.toml
  crates/bootstrap/telemetry/src/lib.rs
  crates/ffmpeg/src/scaler.rs
  crates/pprof/src/lib.rs
  crates/rtmp/Cargo.toml
  crates/rtmp/src/tests/rtmp.rs
  crates/signal/Cargo.toml
  crates/signal/src/lib.rs
  valgrind_suppressions.log
Labels: B-brawl-merged

#286 add powerset to ci
  .github/workflows/ci.yaml
Labels: B-brawl-merged

#287 CI Improvements
  .github/actions/setup-ffmpeg/action.yaml
  .github/actions/setup-rust/action.yaml
  .github/patch-docs.sh
  .github/workflows/ci.yaml
  .github/workflows/crate-release.yaml
  crates/bootstrap/telemetry/Cargo.toml
  crates/bootstrap/telemetry/src/lib.rs
  crates/settings/Cargo.toml
  crates/settings/src/lib.rs
Labels: B-brawl-merged

#289 Change Log Improvements
  .github/labels.yaml
  .github/workflows/change-log.yaml
  .github/workflows/create-crate-release.yaml
  Justfile
  changes.d/README.md
  changes.d/example.toml
  crates/aac/CHANGELOG.md
  crates/amf0/CHANGELOG.md
  crates/av1/CHANGELOG.md
  crates/batching/CHANGELOG.md
  crates/bootstrap/CHANGELOG.md
  crates/bootstrap/derive/CHANGELOG.md
  crates/bootstrap/telemetry/CHANGELOG.md
  crates/bytes-util/CHANGELOG.md
  crates/context/CHANGELOG.md
  crates/expgolomb/CHANGELOG.md
  crates/ffmpeg/CHANGELOG.md
  crates/flv/CHANGELOG.md
  crates/future-ext/CHANGELOG.md
  crates/h264/CHANGELOG.md
  crates/h265/CHANGELOG.md
  crates/h3-webtransport/CHANGELOG.md
  crates/http/CHANGELOG.md
  crates/metrics/CHANGELOG.md
  crates/metrics/derive/CHANGELOG.md
  crates/mp4/CHANGELOG.md
  crates/nutype_enum/CHANGELOG.md
  crates/postcompile/CHANGELOG.md
  crates/pprof/CHANGELOG.md
  crates/rtmp/CHANGELOG.md
  crates/settings/CHANGELOG.md
  crates/signal/CHANGELOG.md
  crates/transmuxer/CHANGELOG.md
  dev-tools/xtask/Cargo.toml
  dev-tools/xtask/src/cmd/change_logs/check_pr.rs
  dev-tools/xtask/src/cmd/change_logs/generate.rs
  dev-tools/xtask/src/cmd/change_logs/mod.rs
  dev-tools/xtask/src/cmd/change_logs/util.rs
  dev-tools/xtask/src/cmd/mod.rs
  dev-tools/xtask/src/cmd/power_set.rs
  dev-tools/xtask/src/cmd/workspace_deps.rs
  release-plz.toml
Labels: B-brawl-merged, change-log-not-required

#290 Migrate FFmpeg Backend
  .github/actions/setup-ffmpeg/action.yaml
  .github/workflows/ci.yaml
  Cargo.lock
  changes.d/pr-290.toml
  crates/ffmpeg/Cargo.toml
  crates/ffmpeg/README.md
  crates/ffmpeg/src/codec.rs
  crates/ffmpeg/src/decoder.rs
  crates/ffmpeg/src/dict.rs
  crates/ffmpeg/src/encoder.rs
  crates/ffmpeg/src/enums/av_channel_order.rs
  crates/ffmpeg/src/enums/av_codec_id.rs
  crates/ffmpeg/src/enums/av_dict_flags.rs
  crates/ffmpeg/src/enums/av_discard.rs
  crates/ffmpeg/src/enums/av_fmt_flags.rs
  crates/ffmpeg/src/enums/av_io_flag.rs
  crates/ffmpeg/src/enums/av_media_type.rs
  crates/ffmpeg/src/enums/av_picture_type.rs
  crates/ffmpeg/src/enums/av_pixel_format.rs
  crates/ffmpeg/src/enums/av_pkt_flags.rs
  crates/ffmpeg/src/enums/av_rounding.rs
  crates/ffmpeg/src/enums/av_sample_format.rs
  crates/ffmpeg/src/enums/av_seek.rs
  crates/ffmpeg/src/enums/mod.rs
  crates/ffmpeg/src/error.rs
  crates/ffmpeg/src/filter_graph.rs
  crates/ffmpeg/src/frame.rs
  crates/ffmpeg/src/io/input.rs
  crates/ffmpeg/src/io/internal.rs
  crates/ffmpeg/src/io/output.rs
  crates/ffmpeg/src/lib.rs
  crates/ffmpeg/src/log.rs
  crates/ffmpeg/src/packet.rs
  crates/ffmpeg/src/rational.rs
  crates/ffmpeg/src/scaler.rs
  crates/ffmpeg/src/snapshots/scuffle_ffmpeg__decoder__tests__test_decoder_audio.snap
  crates/ffmpeg/src/snapshots/scuffle_ffmpeg__decoder__tests__test_decoder_video.snap
  crates/ffmpeg/src/snapshots/scuffle_ffmpeg__encoder__tests__test_encoder_encode_video.snap
  crates/ffmpeg/src/stream.rs
  crates/ffmpeg/src/utils.rs
  crates/nutype_enum/src/lib.rs
  crates/workspace-hack/Cargo.toml
  dev-tools/xtask/src/cmd/change_logs/check_pr.rs
  dev-tools/xtask/src/cmd/change_logs/generate.rs
Labels: B-brawl-merged

#296 try ubicloud
  .github/actions/setup-rust/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/crate-release.yaml
  .github/workflows/create-crate-release.yaml
Labels: B-brawl-merged, change-log-not-required

#300 fix release ci jobs
  .github/workflows/cargo-release-pr.yaml
  .github/workflows/docs-release.yaml
  .github/workflows/release.yaml
Labels: B-brawl-merged, change-log-not-required

#302 add new labels for release prs
  .github/labels.yaml
  .github/workflows/cargo-release-pr.yaml
Labels: B-brawl-merged, change-log-not-required

#310 fix code owners order
  CODEOWNERS
Labels: B-brawl-merged, change-log-not-required

#313 switch to renovate
  .git-blame-ignore-revs
  .github/dependabot.yml
  .github/renovate.json5
  .github/workflows/cargo-release-pr.yaml
Labels: B-brawl-merged, change-log-not-required

#361 add ci job to update lock file every week
  .github/scripts/cargo-update-table.sh
  .github/scripts/patch-docs.sh
  .github/workflows/cargo-update.yaml
  .github/workflows/ci.yaml
Labels: B-brawl-merged, change-log-not-required

#291 Cleanup Xtask
  crates/bootstrap/telemetry/Cargo.toml
  crates/ffmpeg/Cargo.toml
  crates/http/Cargo.toml
  crates/metrics/Cargo.toml
  crates/settings/Cargo.toml
  crates/transmuxer/Cargo.toml
  dev-tools/xtask/src/cmd/power_set/mod.rs
  dev-tools/xtask/src/cmd/power_set/utils.rs
  dev-tools/xtask/src/utils.rs
Labels: B-brawl-merged, change-log-not-required

#366 bump config from 0.14 -> 0.15
  Cargo.lock
  changes.d/pr-366.toml
  crates/settings/Cargo.toml
  crates/workspace-hack/Cargo.toml
Labels: B-brawl-merged, dependencies

#368 bump prometheus-client 0.22 -> 0.23
  Cargo.lock
  changes.d/pr-368.toml
  crates/bootstrap/telemetry/Cargo.toml
  crates/metrics/Cargo.toml
  crates/metrics/examples/Cargo.toml
  crates/metrics/src/prometheus/mod.rs
Labels: B-brawl-merged, dependencies

#367 bumps open-telemetry stack 0.28 -> 0.29
  Cargo.lock
  changes.d/pr-367.toml
  crates/bootstrap/telemetry/Cargo.toml
  crates/bootstrap/telemetry/src/lib.rs
  crates/bootstrap/telemetry/src/opentelemetry.rs
  crates/metrics/Cargo.toml
  crates/metrics/examples/Cargo.toml
  crates/metrics/examples/src/derive.rs
  crates/metrics/examples/src/prometheus.rs
  crates/metrics/src/lib.rs
  crates/metrics/src/prometheus/mod.rs
  crates/workspace-hack/Cargo.toml
  valgrind_suppressions.log
Labels: B-brawl-merged, dependencies

#265 http: rework, tests and docs
  .cargo/config.toml
  .github/workflows/ci.yaml
  Cargo.lock
  Justfile
  assets/cert.pem
  assets/key.pem
  changes.d/pr-265.toml
  crates/bootstrap/telemetry/Cargo.toml
  crates/bootstrap/telemetry/src/lib.rs
  crates/http/Cargo.toml
  crates/http/README.md
  crates/http/examples/Cargo.toml
  crates/http/examples/README.md
  crates/http/examples/src/axum.rs
  crates/http/examples/src/simple_service.rs
  crates/http/examples/src/tcp.rs
  crates/http/src/backend/h3/body.rs
  crates/http/src/backend/h3/mod.rs
  crates/http/src/backend/h3/utils.rs
  crates/http/src/backend/hyper/handler.rs
  crates/http/src/backend/hyper/mod.rs
  crates/http/src/backend/hyper/stream.rs
  crates/http/src/backend/hyper/utils.rs
  crates/http/src/backend/mod.rs
  crates/http/src/backend/quic/mod.rs
  crates/http/src/backend/quic/quinn/config.rs
  crates/http/src/backend/quic/quinn/mod.rs
  crates/http/src/backend/quic/quinn/serve.rs
  crates/http/src/backend/quic/web_transport.rs
  crates/http/src/backend/tcp/config.rs
  crates/http/src/backend/tcp/mod.rs
  crates/http/src/backend/tcp/serve.rs
  crates/http/src/backend/tcp/util.rs
  crates/http/src/body.rs
  crates/http/src/builder.rs
  crates/http/src/error.rs
  crates/http/src/lib.rs
  crates/http/src/server.rs
  crates/http/src/service/clone_factory.rs
  crates/http/src/service/function.rs
  crates/http/src/service/mod.rs
  crates/http/src/service/tower_factory.rs
  crates/http/src/svc/axum.rs
  crates/http/src/svc/function.rs
  crates/http/src/svc/mod.rs
  crates/http/src/svc/tower.rs
  crates/http/src/util.rs
  crates/workspace-hack/Cargo.toml
  dev-tools/xtask/src/cmd/power_set/mod.rs
Labels: B-brawl-merged

#303 improve ffmpeg API
  changes.d/pr-303.toml
  crates/ffmpeg/src/filter_graph.rs
  crates/ffmpeg/src/frame.rs
  crates/ffmpeg/src/lib.rs
  crates/ffmpeg/src/rational.rs
  crates/ffmpeg/src/resampler.rs
  crates/ffmpeg/src/scaler.rs
Labels: B-brawl-merged

#375 fix release-plz config
  release-plz.toml
Labels: B-brawl-merged, change-log-not-required

#377 add ignore for RUSTSEC-2025-0007
  crates/http/Cargo.toml
  crates/workspace-hack/Cargo.toml
  deny.toml
Labels: B-brawl-merged, change-log-not-required

#370 h264 add docs and tests
  Cargo.lock
  changes.d/pr-370.toml
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_header.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_packets.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_fragmented_trailer.snap
  crates/ffmpeg/src/io/snapshots/scuffle_ffmpeg__io__output__tests__test_output_write_mp4_trailer.snap
  crates/flv/Cargo.toml
  crates/flv/src/avc.rs
  crates/flv/src/lib.rs
  crates/h264/Cargo.toml
  crates/h264/README.md
  crates/h264/src/config.rs
  crates/h264/src/enums/aspect_ratio_idc.rs
  crates/h264/src/enums/mod.rs
  crates/h264/src/enums/nal_unit_type.rs
  crates/h264/src/enums/video_format.rs
  crates/h264/src/lib.rs
  crates/h264/src/sps.rs
  crates/h264/src/tests.rs
  crates/mp4/src/boxes/types/avcc.rs
  crates/transmuxer/src/codecs/avc.rs
  crates/transmuxer/src/lib.rs
Labels: B-brawl-merged

#383 fix error handling on previous prs
  crates/ffmpeg/src/encoder.rs
  crates/ffmpeg/src/log.rs
  crates/h264/src/config.rs
  crates/h264/src/sps.rs
Labels: B-brawl-merged, change-log-not-required

#378 run builds on windows + arm
  .config/hakari.toml
  .config/nextest.toml
  .github/actions/ci/clippy/action.yaml
  .github/actions/ci/docs/action.yaml
  .github/actions/ci/dynamic/action.yaml
  .github/actions/ci/fmt/action.yaml
  .github/actions/ci/grind/action.yaml
  .github/actions/ci/hakari/action.yaml
  .github/actions/ci/test/action.yaml
  .github/actions/setup-ffmpeg/action.yaml
  .github/actions/setup-rust/action.yaml
  .github/scripts/ci-matrix-prep.py
  .github/workflows/ci.yaml
  Cargo.lock
  changes.d/pr-378.toml
  crates/batching/src/batch.rs
  crates/batching/src/dataloader.rs
  crates/bootstrap/examples/src/basic.rs
  crates/bootstrap/examples/src/cli.rs
  crates/bootstrap/examples/src/tracing.rs
  crates/bootstrap/src/lib.rs
  crates/bootstrap/src/service.rs
  crates/bootstrap/telemetry/src/lib.rs
  crates/ffmpeg/Cargo.toml
  crates/ffmpeg/src/decoder.rs
  crates/ffmpeg/src/dict.rs
  crates/ffmpeg/src/enums/av_channel_order.rs
  crates/ffmpeg/src/enums/av_codec_id.rs
  crates/ffmpeg/src/enums/av_dict_flags.rs
  crates/ffmpeg/src/enums/av_discard.rs
  crates/ffmpeg/src/enums/av_fmt_flags.rs
  crates/ffmpeg/src/enums/av_io_flag.rs
  crates/ffmpeg/src/enums/av_media_type.rs
  crates/ffmpeg/src/enums/av_picture_type.rs
  crates/ffmpeg/src/enums/av_pixel_format.rs
  crates/ffmpeg/src/enums/av_pkt_flags.rs
  crates/ffmpeg/src/enums/av_rounding.rs
  crates/ffmpeg/src/enums/av_sample_format.rs
  crates/ffmpeg/src/enums/av_seek.rs
  crates/ffmpeg/src/filter_graph.rs
  crates/ffmpeg/src/frame.rs
  crates/ffmpeg/src/io/channel.rs
  crates/ffmpeg/src/io/output.rs
  crates/ffmpeg/src/log.rs
  crates/ffmpeg/src/packet.rs
  crates/http/src/backend/hyper/mod.rs
  crates/postcompile/src/deps.rs
  crates/postcompile/src/lib.rs
  crates/pprof/Cargo.toml
  crates/pprof/README.md
  crates/pprof/examples/src/cpu.rs
  crates/pprof/src/lib.rs
  crates/rtmp/src/tests/rtmp.rs
  crates/settings/src/lib.rs
  crates/signal/README.md
  crates/signal/src/lib.rs
  crates/workspace-hack/Cargo.toml
Labels: B-brawl-merged

#385 try macos builds
  .github/actions/ci/docs/action.yaml
  .github/actions/setup-ffmpeg/action.yaml
  .github/scripts/ci-matrix-prep.py
  .github/scripts/patch-docs.py
  .github/scripts/patch-docs.sh
  crates/batching/src/batch.rs
  crates/batching/src/dataloader.rs
Labels: B-brawl-merged, change-log-not-required

#386 fix minor ci issues missed by previous prs
  .github/scripts/ci-matrix-prep.py
  .github/workflows/change-log.yaml
  .github/workflows/release.yaml
Labels: B-brawl-merged, change-log-not-required

#387 disable renovate lock file maintenance
  .github/renovate.json5
Labels: B-brawl-merged, change-log-not-required

#390 improve developer setup docs
  CONTRIBUTING.md
  dev-tools/xtask/src/cmd/dev_tools.rs
  dev-tools/xtask/src/cmd/mod.rs
Labels: B-brawl-merged, change-log-not-required
